setwd(”/Users/shawn/Documents/勞經“)
setwd(”/Users/shawn/Documents/勞經“)
setwd("~/Documents/勞經")
setwd(”/Users/shawn/Documents“)
setwd(Users/shawn/Documents)
setwd
install.packages("readxl")
library(readxl)
ex_xlsx <- read_excel("A1.xls")
ex_xlsx <- read_excel("/Users/shawn/Documents//Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls")
ex_xlsx <- read_excel("Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls")
ex_xlsx <- read_excel(Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls)
setwd(Users/shawn/Documents/勞經)
getwd()
setwd("/Users/shawn/Documents/勞經")
getwd()
getwd(0)
getwd()
ex_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls")
savehistory("my_history.R")
View(ex_xlsx)
ex1_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls")
View(ex_xlsx)
View(ex1_xlsx)
ex1_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A1.xls")
ex2_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A2.xls")
ex3_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A3.xls")
ex4_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A4.xls")
ex5_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A5.xls")
ex6_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A6.xls")
ex7_xlsx <- read_excel("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/A7.xls")
library(haven)
install.packages("haven")
library(haven)
install.packages("haven")
library(haven)
data_dta <- read_dta("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/treatment.dta")
View(data_dta)
savehistory("my_history.R")
summary()
summary(data_dta)
summary(occ1995)
setwd("/Users/shawn/Documents/勞經")
install.packages("haven")
yes
library(haven)
data_dta <- read_dta("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/Discriptive.dta")
View(data_dta)
summary(data_dta)
data_dta <- mutate
savehistory("my_history.R")
install.packages("haven")
View(data_dta)
summary(data_dta)
data_dta <- mutate
savehistory("my_history.R")
data_dta <- read_dta("/Users/shawn/Documents/勞經/drive-download-20200604T124241Z-001/Descriptive.dta")
View(data_dta)
summary(data_dta)
data_dta <- mutate
savehistory("my_history.R")
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & private == 1), "1", "0" )
install.packages("dplyr")
library(dplyr)
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & private == 1), "1", "0" )
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & Private == 1), "1", "0" )
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & Private == 1)
data_dta <- mutate(data_dta, male_private = (sex ==1 & Private == 1))
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & Private == 1), 1, 0 )
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & Private == 1, 1, 0 ))
View(male_private)
data_dta <- mutate(data_dta, male_nonprivate = ifelse(sex ==1 & Private == 0, 1, 0 ))
data_dta <- mutate(data_dta, female_private = ifelse(sex ==0 & Private == 1, 1, 0 ))
data_dta <- mutate(data_dta, female_nonprivate = ifelse(sex ==0 & Private == 0, 1, 0 ))
data_dta <- mutate(data_dta, male_private = ifelse(sex ==1 & Private == 1, 1, 0 ))
data_dta <- mutate(data_dta, male_nonprivate = ifelse(sex ==1 & Private == 0, 1, 0 ))
data_dta <- mutate(data_dta, female_private = ifelse(sex ==2 & Private == 1, 1, 0 ))
data_dta <- mutate(data_dta, female_nonprivate = ifelse(sex ==2 & Private == 0, 1, 0 ))
savehistory("my_history.R")
